// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HomeNav: typeof import('./src/components/HomeNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    UserHeader: typeof import('./src/components/UserHeader.vue')['default']
    UserSidebar: typeof import('./src/components/UserSidebar.vue')['default']
  }
}

export { }
