// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./components/Action.vue')['default']
    Carousel: typeof import('./components/Carousel.vue')['default']
    Cover: typeof import('./components/Cover.vue')['default']
    DetailHeader: typeof import('./components/DetailHeader.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Gallery: typeof import('./components/Gallery.vue')['default']
    HomeNav: typeof import('./components/HomeNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./components/Search.vue')['default']
    UserSidebar: typeof import('./components/UserSidebar.vue')['default']
  }
}
